### ISSUE TITLE
doesn't migrate repositories which are not :default

### ISSUE THREAD

**Issue by rubycut** [datamapper/dm-migrations#47]
For example:
    DataMapper.setup(:x, :adapter => 'sqlite', :database=> ':memory:')
    DataMapper.repository(:x).auto_migrate!

outputs only:

```
 ~ (0.000229) PRAGMA table_info("servers")
 ~ (0.000023) PRAGMA table_info("customers")
 ~ (0.204847) SET sql_auto_is_null = 0
 ~ (0.206043) SET SESSION sql_mode = 'ANSI,NO_BACKSLASH_ESCAPES,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_UNSIGNED_SUBTRACTION,TRADITIONAL'

```

Doesn't really upgrade anything.

**Comment by darraghbuckley** [comment]
This is a pretty old issue, but should be addressed by https://github.com/datamapper/dm-migrations/pull/60.

**Comment by tpitale** [comment]
I think you're right. Calling it resolved.
