### ISSUE TITLE
Running tests on migrations as given in example fails

### ISSUE THREAD

**Issue by ksinkar** [datamapper/dm-migrations#59]
There is [example code](https://github.com/datamapper/dm-migrations/blob/master/examples/sample_migration_spec.rb) that shows how to write and run specs for migrations. Unfortunately the code uses some custom hack [lib/spec/example/migration_example_group.rb](https://github.com/datamapper/dm-migrations/blob/master/lib/spec/example/migration_example_group.rb) that is not made available to the Gem in general and hence users cannot use it.

I am not exactly sure how to go about resolving this. If there are any pointers, would be happy to send a pull request.

**Comment by tpitale** [comment]
This file is distributed in the gem: https://github.com/datamapper/dm-migrations/blob/master/lib/spec/example/migration_example_group.rb

But, it requires `spec` file in it, which is a previous version of rspec.

However, this file is meant only as an example. It's meant to be used in your own code in your own way, requiring some modification, and in this case copying of the file into your code.

To update this example to work universally, with everyone's code, would be nearly impossible.
